// Auto-generated by scripts/gen-avatar-manifest.mjs — do not edit by hand.
// Maps an athlete name-slug -> the raster photo extension present in
// /public/avatars. Regenerate:  node scripts/gen-avatar-manifest.mjs
export const AVATAR_PHOTOS: Record<string, string> = {};
